version: 2

templates:
  golang-template: &golang-template
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/u-root/cpu
    environment:
      - GOPATH: "/go"
      - CGO_ENABLED: 0

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    <<: *golang-template
    steps:
      - checkout
      - run: go env
      - run: go build ./...
      - run: go test -timeout 15m -v ./...
      - run: |
          go get github.com/mitchellh/gox
          gox -os="linux" -arch="amd64 arm arm64 ppc64 ppc64le s390x mips mipsle mips64 mips64le" ./...
